In [1]:
import numpy as np

In [10]:
a = np.array([0,1,2,0,3,4]).reshape(2,3)

In [21]:
b = np.array([0,0,10,30,20,40]).reshape(3,2)

In [28]:
c = np.array([0,1])

In [22]:
a

array([[0, 1, 2],
       [0, 3, 4]])

In [23]:
b

array([[ 0,  0],
       [10, 30],
       [20, 40]])

In [29]:
c

array([0, 1])

In [18]:
############## Transpose an array 

In [24]:
a.T

array([[0, 0],
       [1, 3],
       [2, 4]])

In [20]:
b.T

array([[ 0, 10, 20],
       [ 0, 30, 40]])

In [25]:
############# Dot Product 
#  P@Q
#  np.matmul(P,Q)
#  np.dot(P,Q)

In [26]:
a@b

array([[ 50, 110],
       [110, 250]])

In [27]:
b@a

array([[  0,   0,   0],
       [  0, 100, 140],
       [  0, 140, 200]])

In [30]:
a@c # error is expected 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [31]:
c@a

array([0, 3, 4])

In [ ]:
############### Hadamard Product
#  P*Q
#  np.multiply(P,Q)

In [32]:
a*b # error is expected 

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [34]:
a*b.T

array([[  0,  10,  40],
       [  0,  90, 160]])